### ISSUE TITLE
increasing CPU and memory usage after running for several hours

### ISSUE THREAD

**Issue by timbleck** [brutella/hklifx#22]
After starting `hklifx` on my C.H.I.P. (ARMv7, Debian based Linux) i do see an increase of CPU and memory usage after running for several hours in the background. Regarding `top` and `ps` looks like hklifx is starting more and more threads that are not closed anymore. Even looks like the process then crashes at some point (see [hklifx-log.txt](https://github.com/brutella/hklifx/files/418675/hklifx-log.txt)).

**Comment by steventroughtonsmith** [comment]
I see the same on my iMac with 24GB RAM—it expands to fill all available memory over time. Not safe to keep running for long periods

**Comment by brutella** [comment]
I think the reason why this happens is that the connection to the HomeKit clients is never closed. iOS tries to keep the connection alive as long as possible. We should set a reasonable connection timeout. I've opened an issue in the [hc](https://github.com/brutella/hc/issues/64) project.

**Comment by broglea** [comment]
I run this on my raspberry pi model b+ and get OOM after it has been running for about a day.

**Comment by medazzouzi** [comment]
Hello,
I run or on my synology or has gone OOM in a day.

Le 4 oct. 2016 ? 18:54, Austin Brogle <notifications@github.com<mailto:notifications@github.com>> a ?crit :

I run this on my raspberry pi model b+ and get OOM after it has been running for about a day.

##

**Comment by brutella** [comment]
I've added a [possible fix](https://github.com/brutella/hc/commit/e2d915f38ed0961bb25d048f2b7bd84e168cb9d2) to the hc project.

Since hklifx and hc now support [vendor directories](https://golang.org/cmd/go/#hdr-Vendor_Directories), you don't have to manually fetch the changes of all dependencies. Just fetch the changes of the hklifx master branch.

**Comment by steventroughtonsmith** [comment]
Will keep an eye on it and report back. It does still seem to be climbing in memory usage before any clients interact with it through the UI. As much as 0.5MB a second for a period, every few seconds

**Comment by lstemple** [comment]
To add my experience -- I too had the out-of memory error on an Raspberry Pi 2 Model b, after about 5 hours. I was redirecting std-err to a log file which ended up being around 50MB. There appears to be a goroutine leak of some kind, since the log contained about 90k goroutine stack traces -- the vast majority of which looked like this:

`goroutine 1444 [chan send, 440 minutes]:
hklifx/vendor/github.com/pdf/golifx/protocol/v2/device.(*Device).Handle(0x10918000, 0x116119f0)
	/home/pi/dev/go/src/hklifx/vendor/github.com/pdf/golifx/protocol/v2/device/device.go:571 +0x70
hklifx/vendor/github.com/pdf/golifx/protocol.(*V2).process(0x10877570, 0x116119f0, 0x109fec00)
	/home/pi/dev/go/src/hklifx/vendor/github.com/pdf/golifx/protocol/v2.go:552 +0x8254
created by hklifx/vendor/github.com/pdf/golifx/protocol.(*V2).dispatcher
	/home/pi/dev/go/src/hklifx/vendor/github.com/pdf/golifx/protocol/v2.go:356 +0x640`

I hope this helps! I am really enjoying learning from this project 👍

**Comment by brutella** [comment]
In my experience all other [hc](https://github.com/brutella/hc) based projects run without memory issues for month. I think that the memory leak happens in [golifx](https://github.com/pdf/golifx) – but I currently don't have time to look into that.

**Comment by taz030485** [comment]
Yeah I'm getting OOM errors as well.
Launched at 11:52pm and crashed sometime around 4:22am
stdout stderr both logged out [log.txt](https://github.com/brutella/hklifx/files/765386/log.txt)

**Comment by bland328** [comment]
I opened Issue 31 (https://github.com/brutella/hklifx/issues/31) just minutes ago, before realizing my hklifx problems might also be due to OOM failures.

I'm now witnessing that after running for just 20 minutes, hklifxd is (according to top) consuming 10% of memory, and still climbing.

**Comment by pdf** [comment]
@brutella I'm not sure how you're doing vendoring, or I'd submit a PR, but if you make this change:

```go
diff --git a/hklifxd.go b/hklifxd.go
index 4e67063..1eac00e 100644
--- a/hklifxd.go
+++ b/hklifxd.go
@@ -47,7 +47,7 @@ func Connect() {
 
        client.SetDiscoveryInterval(30 * time.Second)
 
-       sub, _ := client.NewSubscription()
+       sub := client.Subscribe()
        for {
                event := <-sub.Events()
                switch event.(type) {
@@ -81,7 +81,7 @@ func NewDevice(device common.Device) {
        if light, ok := device.(common.Light); ok {
                hkLight := GetHKLight(light)
 
-               hkLight.sub, _ = light.NewSubscription()
+               hkLight.sub = light.Subscribe()
                for {
                        event := <-hkLight.sub.Events()
                        switch event.(type) {
@@ -115,7 +115,7 @@ func NewDevice(device common.Device) {
 func ExpireDevice(device common.Device) {
        if light, ok := device.(common.Light); ok {
                if hkLight, found := lights[light.ID()]; found == true {
-                       light.CloseSubscription(hkLight.sub)
+                       hkLight.sub.Close()
                        hkLight.transport.Stop()
 
                        delete(lights, light.ID())
```

And update golifx to v1.0.1, I've made changes to golifx that may help, but I don't have any Apple stuff to test this particular code with.  The changes are not well tested by me at this stage though, as I've had very little time to work that code for quite a while.

If the issue is not resolved by this, users who can reproduce the problem will need to provide some profiling (ie - pprof) data to have any hope of working out where the leak is.

**Comment by brutella** [comment]
@pdf Thanks, golifx v1.0.1 is now available in [golifx-dnssd](https://github.com/brutella/hklifx/tree/golifx-dnssd) branch. This branch also includes the [dnssd](https://github.com/brutella/hc/tree/dnssd) branch from `hc` which eliminates connection issues.

Everybody interested in those changes, do the following:

1. Checkout the golifx-dnssd branch `git checkout golifx-dnssd`
2. Run `go get`
3. Run `hklifxd.go`

**Comment by brutella** [comment]
Anyone still experiences this issue?
